package authsvr

import "er"

const (
	_E_AUTH_SRV = 0x3000

	_E_AUTH_SRV_TIMEOUT     = _E_AUTH_SRV | er.IMPT_UNRECOVERABLE | er.ET_INTERNAL | er.EI_TIMEOUT | 0x1
	_E_INVALID_AUTH_REQUEST = _E_AUTH_SRV | er.IMPT_THREAT | er.ET_INTERNAL | er.EI_INVALID_REQUEST | 0x2
	_E_USER_NOT_LOGIN       = _E_AUTH_SRV | er.IMPT_REMARKABLE | er.ET_INTERACTION | er.EI_INVALID_REQUEST | 0x3

	_E_INVALID_AUTH_RESULT = _E_AUTH_SRV | er.IMPT_THREAT | er.ET_INTERNAL | er.EI_ILLEGAL_RESULT | 0x4
	_E_LOGOUT_FAIL         = _E_AUTH_SRV | er.IMPT_REMARKABLE | er.ET_INTERACTION | er.EI_ILLEGAL_PARAMETER | 0x5
)
