package main

import "er"

const (
	_E_FWB = 0x8000

	_E_CMD_INVALID_CLIENT = _E_FWB | er.IMPT_REMARKABLE | er.ET_INTERACTION | er.ET_INVALID_REQUEST | 0x1

	_E_INVALID_CMD = _E_FWB | er.IMPT_REMARKABLE | er.ET_INTERNAL | er.ET_INVALID_REQUEST | 0x2

	_E_CMD_NOT_EXEC = _E_FWB | er.IMPT_RECOVERABLE | er.ET_INTERACTION | er.ET_INVALID_REQUEST | 0x3

	_E_CMD_PAYLOAD_NOT_ENCODABLE = _E_FWB | er.IMPT_THREAT | er.ET_INTERNAL | er.ET_ILLEGAL_PARAMETER | 0x4

	_E_CMD_PAYLOAD_NOT_DECODABLE = _E_FWB | er.IMPT_THREAT | er.ET_INTERNAL | er.ET_ILLEGAL_PARAMETER | 0x5

	_E_MISSING_GAME_SETTINGS = _E_FWB | er.IMPT_UNRECOVERABLE | er.ET_SETTINGS | er.ET_MISSING_DATA | 0x6

	_E_INVALID_SETTINGS = _E_FWB | er.IMPT_UNRECOVERABLE | er.ET_SETTINGS | er.ET_ILLEGAL_PARAMETER | 0x7

	_E_NO_PROPER_PROFILE = _E_FWB | er.IMPT_UNRECOVERABLE | er.ET_SETTINGS | er.ET_ILLEGAL_PARAMETER | 0x8
)
