package ssvr

import (
	"er"
)

const (
	_E_SGS_SSVR = 0x2000

	//E_JOIN_SESSION_INVALID_CLIENT send join session request without valid client
	_E_JOIN_SESSION_INVALID_CLIENT = _E_SGS_SSVR | er.IMPT_REMARKABLE | er.ET_INTERACTION | er.ET_INVALID_REQUEST | 0x1

	_E_INVALID_SERVER_PARAM = _E_SGS_SSVR | er.IMPT_UNRECOVERABLE | er.ET_INTERNAL | er.ET_ILLEGAL_PARAMETER | 0x2

	_E_BIND_CONN_INVALID_CLIENT = _E_SGS_SSVR | er.IMPT_REMARKABLE | er.ET_INTERACTION | er.ET_INVALID_REQUEST | 0x3

	_E_SESSION_INVALID_COMMAND = _E_SGS_SSVR | er.IMPT_REMARKABLE | er.ET_INTERNAL | er.ET_ILLEGAL_PARAMETER | 0x4

	_E_SESSION_INVALID_CLIENT = _E_SGS_SSVR | er.IMPT_REMARKABLE | er.ET_INTERNAL | er.ET_ILLEGAL_PARAMETER | 0x5

	_E_CLIENT_CONNECTION_FAIL = _E_SGS_SSVR | er.IMPT_REMARKABLE | er.ET_INTERACTION | er.ET_NETWORK | 0x6
)
